In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
import numpy as np

In [ ]:
a2 = np.array([[1,2,3],
                [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2.ndim

2

In [ ]:
a3 = np.array ([[[1,2,3],
                [4,5,6]],
                [[7,8,9],
                [10,11,12]]])

In [ ]:
simple_python = [1,2,3]
simple_python

[1, 2, 3]

In [ ]:
for num in simple_python:
  print(num*2)

2
4
6


In [ ]:
a

array([1, 2, 3])

In [ ]:
a>2

array([False, False,  True])

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a2 + a

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
import numpy as np

In [ ]:
a = np.array ([1,2,3])
a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2.ndim

2

In [ ]:
a2.size

6

In [ ]:
a2.ndim

2

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.dtype
type(a2)

numpy.ndarray

In [ ]:
import pandas as pd

pd.DataFrame(a2)

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
np.ones(shape = (10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros(shape = (7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.random.random(size = (0,100))

array([], shape=(0, 100), dtype=float64)

In [ ]:
np.random.random(size = (3,5))

array([[0.60622538, 0.00431657, 0.90891053, 0.54428089, 0.13893636],
       [0.64394131, 0.7784217 , 0.44399562, 0.54304269, 0.99141618],
       [0.44162301, 0.62900098, 0.39509473, 0.68895768, 0.66546669]])

In [ ]:
np.random.seed(42)
np.random.random()

0.3745401188473625

In [ ]:
random_nums = np.random.randint(1,10, size = (3,7))
random_nums

array([[8, 5, 7, 3, 7, 8, 5],
       [4, 8, 8, 3, 6, 5, 2],
       [8, 6, 2, 5, 1, 6, 9]])

In [ ]:
random_nums

array([[8, 5, 7, 3, 7, 8, 5],
       [4, 8, 8, 3, 6, 5, 2],
       [8, 6, 2, 5, 1, 6, 9]])

In [ ]:
random_nums[0][0]

8

In [ ]:
random_nums[0:2]

array([[8, 5, 7, 3, 7, 8, 5],
       [4, 8, 8, 3, 6, 5, 2]])

In [ ]:
random_nums[2][0:2]

array([8, 6])

In [ ]:
a= np.random.randint(0,10)
b =np.ones(shape=(3,5))
a

0

In [ ]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a+b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
c=np.ones(shape =(5,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
d= b + c.T
d

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [ ]:
l= np.ones(shape = (3,5))
l

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x=d-l
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.square(d)

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [ ]:
np.mean(x)

1.0

In [ ]:
np.max(d)

2.0

In [ ]:
np.min(d)

2.0

In [ ]:
d.ndim

2

In [ ]:
massive_array = np.random.random

In [ ]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
reshaped_array = np.reshape(c, (3,5,1))

In [ ]:
c.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array1= np.random.randint(10, size =(3,3))
array1

array([[0, 7, 7],
       [2, 0, 7],
       [2, 2, 0]])

In [ ]:
array2=np.random.randint(10, size = (3,2))
array2

array([[4, 9],
       [6, 9],
       [8, 6]])

In [ ]:
dot_product_result = np.dot(array1,array2)
dot_product_result

array([[ 98, 105],
       [ 64,  60],
       [ 20,  36]])

In [ ]:
arr1 = np.random.randint(10, size=(4,3))
arr1



array([[9, 1, 9],
       [0, 7, 0],
       [8, 5, 6],
       [9, 6, 9]])

In [ ]:
arr2 = np.random.randint(10, size=(4,3))
arr2

array([[0, 3, 9],
       [5, 5, 4],
       [0, 7, 4],
       [4, 6, 3]])

In [ ]:
dot_result = np.dot(arr1,arr2.T)
dot_result

array([[ 84,  86,  43,  69],
       [ 21,  35,  49,  42],
       [ 69,  89,  59,  80],
       [ 99, 111,  78,  99]])

In [ ]:
new1 = np.random.randint(10, size= (3,2))
new1

array([[1, 9],
       [2, 0],
       [7, 2]])

In [ ]:
new2 = np.random.randint(10, size = (3,2))
new2

array([[9, 6],
       [9, 4],
       [9, 4]])

In [ ]:
new1 >= new2

array([[False,  True],
       [False, False],
       [False, False]])

In [ ]:
new1 > 7

array([[False,  True],
       [False, False],
       [False, False]])

In [ ]:
new1 == new2

array([[False, False],
       [False, False],
       [False, False]])

In [ ]:
array_to_sort = new2
array_to_sort

array([[9, 6],
       [9, 4],
       [9, 4]])

In [ ]:
sorted_array = np.sort(array_to_sort, axis = -1)
sorted_array

array([[6, 9],
       [4, 9],
       [4, 9]])

In [ ]:
new1

array([[1, 9],
       [2, 0],
       [7, 2]])

In [ ]:
array_to_sort

array([[9, 6],
       [9, 4],
       [9, 4]])

In [ ]:
sorted_indecex = np.argsort(array_to_sort, axis = 0)
sorted_indecex

array([[0, 1],
       [1, 2],
       [2, 0]])

In [ ]:
new1

array([[1, 9],
       [2, 0],
       [7, 2]])

In [ ]:
np.max(new1)

9

In [ ]:
np.min(new1)

0

In [ ]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
a1.var()

0.6666666666666666

In [ ]:
np.random.rand(100)

array([0.08087297, 0.42831447, 0.6884999 , 0.0581936 , 0.91521373,
       0.44235223, 0.23978736, 0.09387329, 0.182866  , 0.934614  ,
       0.63827059, 0.51669626, 0.65711133, 0.4356729 , 0.73003932,
       0.04771613, 0.56603721, 0.15864645, 0.12016465, 0.34187967,
       0.09179907, 0.09415699, 0.31141331, 0.97951053, 0.17533027,
       0.0171611 , 0.76336442, 0.80691298, 0.34630432, 0.46467381,
       0.64977368, 0.04805892, 0.94914573, 0.88668039, 0.26089362,
       0.01530454, 0.93343631, 0.50103988, 0.53937745, 0.68396377,
       0.61585116, 0.9438916 , 0.9442516 , 0.86719893, 0.6364036 ,
       0.80094929, 0.67716834, 0.57336704, 0.12850035, 0.81120418,
       0.82063948, 0.62593967, 0.82042684, 0.65148477, 0.20668436,
       0.27396113, 0.21458912, 0.37725908, 0.03896313, 0.61825388,
       0.33655421, 0.65572264, 0.38539662, 0.68161367, 0.34062457,
       0.26069453, 0.49603745, 0.69289036, 0.3483366 , 0.93664815,
       0.03918633, 0.41794603, 0.96758055, 0.54797188, 0.42347

In [ ]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
a1.argmin()

0

In [ ]:
a1.argmax()

2